# Generated by Django 5.0.6 on 2024-06-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelname',
            options={'verbose_name': 'مودل دجانحو ', 'verbose_name_plural': 'مودل دجانحو s'},
        ),
        migrations.AlterField(
            model_name='modelname',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
